### ISSUE TITLE
endless reboot

### ISSUE THREAD

**Issue by Ladduro** [j4nf4b3l/MDMPatcher-Universal#11]
I have an iPad 8th Gen with 14.5.1 I disabled SIP and got the program to run but I still see the mdm after the device reboot, can I please get some help?

**Comment by MerBudd** [comment]
tried on a friend's old ipad 6,11. and it didn't work either. i guess it doesn't work on ipads

**Comment by j4nf4b3l** [comment]
It works. Just make sure to clean restore the iPad, do NOT connect to Wi-Fi while activating, do that through finder / iTunes. 
Then run the tool and it should be fixed...
