### ISSUE TITLE
No DMG for Patcher

### ISSUE THREAD

**Issue by mafaesto** [j4nf4b3l/MDMPatcher-Universal#13]
As the title says, there isn't a DMG file available any longer. Would you be able to reupload it?

**Comment by zvadym** [comment]
+1 to this request!

**Comment by zacharywilliams05** [comment]
+1 more!

**Comment by g10drasingh** [comment]
+1 for this

**Comment by IMMILDEW** [comment]
+1

**Comment by carlitosuave** [comment]
+1

**Comment by neauxm** [comment]
+1 is this project abandoned?

**Comment by mbooij** [comment]
+1

**Comment by j4nf4b3l** [comment]
Well. If there is such a demand for it, I will reupload the DMG...
:)

**Comment by kjaerby** [comment]
> Well. If there is such a demand for it, I will reupload the DMG... :)

would be awesome!

**Comment by sanch03** [comment]
+1 Would love that

**Comment by jasecyber** [comment]
Would be nice

**Comment by ipsingh88** [comment]
Need the DMG , please reupload

**Comment by j4nf4b3l** [comment]
Done. Enjoy :)
