### ISSUE TITLE
getting the following error on trying to run MDMPatcher_Universal_v1.dmg

### ISSUE THREAD

**Issue by ipsingh88** [j4nf4b3l/MDMPatcher-Universal#14]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               MDMPatcher Universal [52939]
Path:                  /private/var/folders/*/MDMPatcher Universal.app/Contents/MacOS/MDMPatcher Universal
Identifier:            com.noone.mdmpatch
Version:               1.0 (1)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-03-22 10:20:34.4080 -0400
OS Version:            macOS 13.2.1 (22D68)
Report Version:        12
Anonymous UUID:        E6FE7786-0655-5F66-C24E-BFFDA8B310E5

Time Awake Since Boot: 4100 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @loader_path/../Frameworks/libusbmuxd.dylib
Referenced from: <7D6F0D01-0364-314E-BEF5-EFCDEB0682EE> /private/var/folders/*/MDMPatcher Universal.app/Contents/MacOS/MDMPatcher Universal
Reason: tried: '/private/var/folders/_8/yr62ymjn3s1br5mdph2xzgp40000gn/T/AppTranslocation/F1A52AE7-C962-4A7D-9F07-23555A381509/d/MDMPatcher Universal.app/Contents/MacOS/../Frameworks/libusbmuxd.dylib' (code signature in <C64B8859-B814-391D-B5DF-40098B9EEFEA> '/private/var/folders/_8/yr62ymjn3s1br5mdph2xzgp40000gn/T/AppTranslocation/F1A52AE7-C962-4A7D-9F07-23555A381509/d/MDMPatcher Universal.app/Contents/Frameworks/libusbmuxd.dylib' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/System/Volumes/Preboot/Cryptexes/OS@loader_path/../Frameworks/libusbmuxd.dylib' (no such file), '/private/var/folders/_8/yr62ymjn3s1br5mdph2xzgp40000gn/T/AppTr
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   Rosetta Runtime Routines	       0x10085c9a8 ???
1   <translation info unavailable>	       0x1008eff14 ???
2   dyld                          	       0x200c08d07 abort_with_payload_wrapper_internal + 82
3   dyld                          	       0x200c08d39 abort_with_payload + 9
4   dyld                          	       0x200b901e1 dyld4::halt(char const*) + 375
5   dyld                          	       0x200b8d660 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4502
6   dyld                          	       0x200b8c281 start + 2289

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffdc4614 0x7ff7ffdc0000 + 17940
1   runtime                       	    0x7ff7ffdd0530 0x7ff7ffdc0000 + 66864
2   runtime                       	    0x7ff7ffdd1f30 0x7ff7ffdc0000 + 73520

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000030539a860   x3: 0x00000000000000ee
    x4: 0x000000030539a460   x5: 0x0000000000000000   x6: 0x000000030539a830   x7: 0x0000002000b92844
    x8: 0x000000030539a460   x9: 0x0000000000000000  x10: 0x00000000000000ee  x11: 0x000000030539a460
   x12: 0x00000000000000ee  x13: 0x000000030539a860  x14: 0x0000000000000001  x15: 0x0000000000000006
   x16: 0x0000000000000209  x17: 0x0000000000000000  x18: 0x80000001088bdb80  x19: 0x0000000100852000
   x20: 0x00000000000007ff  x21: 0x00000001088c2fa0  x22: 0xffffffffffffffff  x23: 0x000000010085c97c
   x24: 0x0000000200c08d07  x25: 0x000000010085c248  x26: 0x00000001008edc00  x27: 0x0000000000000000
   x28: 0x0000000200befb4a   fp: 0x000000002c000000   lr: 0x00000001008eff14
    sp: 0x00000001088bdb80   pc: 0x000000010085c9a8 cpsr: 0x80001000
   far: 0x0000000108e1f010  esr: 0x56000080  Address size fault

Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x200b86000 -        0x200c1dfff dyld (*) <bba77709-6cad-3592-ab03-09d0f7b8610e> /usr/lib/dyld
    0x7ff7ffdc0000 -     0x7ff7ffdeffff runtime (*) <f066db2c-ed38-3f37-8d21-81d15fa908fe> /usr/libexec/rosetta/runtime

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1936K resident=0K(0%) swapped_out_or_unallocated=1936K(100%)
Writable regions: Total=156.9M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=156.9M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Rosetta Arena                     4096K        2 
Rosetta Generic                    900K      222 
Rosetta IndirectBranch              32K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack                20K        2 
Rosetta Thread Context              20K        2 
Stack                             8176K        1 
Stack Guard                       56.0M        1 
VM_ALLOCATE                       15.5M        7 
VM_ALLOCATE (reserved)              16K        1         reserved VM address space (unallocated)
__DATA                             144K        6 
__DATA_CONST                        32K        1 
__DATA_DIRTY                        16K        1 
__LINKEDIT                         480K        8 
__TEXT                            1488K        4 
dyld private memory                512K        2 
mapped file                        6.6G       34 
===========                     =======  ======= 
TOTAL                              6.9G      296 
TOTAL, minus reserved VM space     6.9G      296 

-----------
Full Report
-----------

{"app_name":"MDMPatcher Universal","timestamp":"2023-03-22 10:20:34.00 -0400","app_version":"1.0","slice_uuid":"7d6f0d01-0364-314e-bef5-efcdeb0682ee","build_version":"1","platform":1,"bundleID":"com.noone.mdmpatch","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.2.1 (22D68)","roots_installed":0,"name":"MDMPatcher Universal","incident_id":"01A3E127-163B-4A85-B14A-C547AC85C3F4"}
{
  "uptime" : 4100,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,3",
  "coalitionID" : 3169,
  "osVersion" : {
    "train" : "macOS 13.2.1",
    "build" : "22D68",
    "releaseType" : "User"
  },
  "captureTime" : "2023-03-22 10:20:34.4080 -0400",
  "incident" : "01A3E127-163B-4A85-B14A-C547AC85C3F4",
  "pid" : 52939,
  "translated" : true,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-03-22 10:20:34.2848 -0400",
  "procStartAbsTime" : 100363680161,
  "procExitAbsTime" : 100366570505,
  "procName" : "MDMPatcher Universal",
  "procPath" : "\/private\/var\/folders\/*\/MDMPatcher Universal.app\/Contents\/MacOS\/MDMPatcher Universal",
  "bundleInfo" : {"CFBundleShortVersionString":"1.0","CFBundleVersion":"1","CFBundleIdentifier":"com.noone.mdmpatch"},
  "storeInfo" : {"deviceIdentifierForVendor":"5248413F-71E9-55D7-8F16-69E02E7CAC36","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.noone.mdmpatch",
  "crashReporterKey" : "E6FE7786-0655-5F66-C24E-BFFDA8B310E5",
  "throttleTimeout" : 2147483647,
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @loader_path\/..\/Frameworks\/libusbmuxd.dylib","Referenced from: <7D6F0D01-0364-314E-BEF5-EFCDEB0682EE> \/private\/var\/folders\/*\/MDMPatcher Universal.app\/Contents\/MacOS\/MDMPatcher Universal","Reason: tried: '\/private\/var\/folders\/_8\/yr62ymjn3s1br5mdph2xzgp40000gn\/T\/AppTranslocation\/F1A52AE7-C962-4A7D-9F07-23555A381509\/d\/MDMPatcher Universal.app\/Contents\/MacOS\/..\/Frameworks\/libusbmuxd.dylib' (code signature in <C64B8859-B814-391D-B5DF-40098B9EEFEA> '\/private\/var\/folders\/_8\/yr62ymjn3s1br5mdph2xzgp40000gn\/T\/AppTranslocation\/F1A52AE7-C962-4A7D-9F07-23555A381509\/d\/MDMPatcher Universal.app\/Contents\/Frameworks\/libusbmuxd.dylib' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '\/System\/Volumes\/Preboot\/Cryptexes\/OS@loader_path\/..\/Frameworks\/libusbmuxd.dylib' (no such file), '\/private\/var\/folders\/_8\/yr62ymjn3s1br5mdph2xzgp40000gn\/T\/AppTr"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":313172,"threadState":{"x":[{"value":6},{"value":1},{"value":12972566624},{"value":238},{"value":12972565600},{"value":0},{"value":12972566576},{"value":137451087940},{"value":12972565600},{"value":0},{"value":238},{"value":12972565600},{"value":238},{"value":12972566624},{"value":1},{"value":6},{"value":521},{"value":0},{"value":9223372041293126528},{"value":4303691776},{"value":2047},{"value":4438372256},{"value":18446744073709551615},{"value":4303735164},{"value":8602553607,"symbolLocation":82,"symbol":"abort_with_payload_wrapper_internal"},{"value":4303733320},{"value":4304329728},{"value":0},{"value":8602450762,"symbolLocation":10,"symbol":"__abort_with_payload"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4304338708},"cpsr":{"value":2147487744},"fp":{"value":738197504},"sp":{"value":4438350720},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":4303735208,"matchesCrashFrame":1},"far":{"value":4443992080}},"frames":[{"imageOffset":4303735208,"region":"Rosetta Runtime Routines","symbolLocation":10664,"imageIndex":0},{"imageOffset":4304338708,"region":"<translation info unavailable>","imageIndex":0},{"imageOffset":535815,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":82,"imageIndex":1},{"imageOffset":535865,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":1},{"imageOffset":41441,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":1},{"imageOffset":30304,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4502,"imageIndex":1},{"imageOffset":25217,"symbol":"start","symbolLocation":2289,"imageIndex":1}]},{"id":313209,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":17940,"imageIndex":2},{"imageOffset":66864,"imageIndex":2},{"imageOffset":73520,"imageIndex":2}]}],
  "usedImages" : [
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8602017792,
    "size" : 622592,
    "uuid" : "bba77709-6cad-3592-ab03-09d0f7b8610e",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703126257664,
    "size" : 196608,
    "uuid" : "f066db2c-ed38-3f37-8d21-81d15fa908fe",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  }
],
  "sharedCache" : {
  "base" : 140703487000576,
  "size" : 21474836480,
  "uuid" : "4ca2b729-8206-3c63-badd-faa0225ab773"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1936K resident=0K(0%) swapped_out_or_unallocated=1936K(100%)\nWritable regions: Total=156.9M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=156.9M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nRosetta Arena                     4096K        2 \nRosetta Generic                    900K      222 \nRosetta IndirectBranch              32K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack                20K        2 \nRosetta Thread Context              20K        2 \nStack                             8176K        1 \nStack Guard                       56.0M        1 \nVM_ALLOCATE                       15.5M        7 \nVM_ALLOCATE (reserved)              16K        1         reserved VM address space (unallocated)\n__DATA                             144K        6 \n__DATA_CONST                        32K        1 \n__DATA_DIRTY                        16K        1 \n__LINKEDIT                         480K        8 \n__TEXT                            1488K        4 \ndyld private memory                512K        2 \nmapped file                        6.6G       34 \n===========                     =======  ======= \nTOTAL                              6.9G      296 \nTOTAL, minus reserved VM space     6.9G      296 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "6112e3d2fc54bc3389840661",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "63f8017d238e7b23a1f300f1"
      },
      "deploymentId" : 240000356
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro18,3, BootROM 8419.80.7, proc 10:8:2 processors, 16 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: Color LCD, 3024 x 1964 Retina, Main, MirrorOff, Online
Display: 24N1, 1920 x 1080 (1080p FHD - Full High Definition), MirrorOff, Online
Memory Module: LPDDR5, Samsung
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Nov 30 2022 02:17:16 version 20.10.965.13.8.7.131 FWID 01-1251c18d
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by j4nf4b3l** [comment]
Turn off sip and try again. Then it should work.
