### ISSUE TITLE
Unable to remove MDM profile

### ISSUE THREAD

**Issue by demhademha** [j4nf4b3l/MDMPatcher-Universal#17]
iPad: iPad seven
Version: 16.3.1
Profile: lightspeed
Successfully patched and device, reboot, but profile exists

**Comment by j4nf4b3l** [comment]
Make a clean restore, activate over Finder, then run the tool. Make sure to **NOT connect to wifi** before you ran the patch.

**Comment by prescientmoon** [comment]
@j4nf4b3l any info about how to make a clean restore?
