### ISSUE TITLE
App Crashes on macOS Big Sur 11.7.5 

### ISSUE THREAD

**Issue by D1Advocatus** [j4nf4b3l/MDMPatcher-Universal#18]
The app crashes on macOS Big Sur 11.7.5 . Please crash  log below.

Process:               MDMPatcher Universal [2462]
Path:                  /Applications/MDMPatcher Universal.app/Contents/MacOS/MDMPatcher Universal
Identifier:            com.noone.mdmpatch
Version:               1.0 (1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           MDMPatcher Universal [2462]
User ID:               501

Date/Time:             2023-04-02 22:01:08.669 +0100
OS Version:            macOS 11.7.5 (20G1225)
Report Version:        12
Anonymous UUID:        CC5F8DED-A4F2-1E04-60BC-6C283A82C094

Time Awake Since Boot: 3300 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x5] Code Signature

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/../Frameworks/libusbmuxd.dylib
  Referenced from: /Applications/MDMPatcher Universal.app/Contents/MacOS/MDMPatcher Universal
  Reason: no suitable image found.  Did find:
	/Applications/MDMPatcher Universal.app/Contents/MacOS/../Frameworks/libusbmuxd.dylib: code signature in (/Applications/MDMPatcher Universal.app/Contents/MacOS/../Frameworks/libusbmuxd.dylib) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)
	/Applications/MDMPatcher Universal.app/Contents/MacOS/../Frameworks/libusbmuxd.dylib: stat() failed with errno=1
	/Applications/MDMPatcher Universal.app/Contents/MacOS/../Frameworks/libusbmuxd.dylib: code signature in (/Applications/MDMPatcher Universal.app/Contents/MacOS/../Frameworks/libusbmuxd.dylib) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)
	/Applications/MDMP

Binary Images:
       0x10fec2000 -        0x10ff1dfff +com.noone.mdmpatch (1.0 - 1) <7D6F0D01-0364-314E-BEF5-EFCDEB0682EE> /Applications/MDMPatcher Universal.app/Contents/MacOS/MDMPatcher Universal
       0x1116e3000 -        0x11177efff  dyld (852.2) <20FFCE1A-0F70-3A4A-A860-D8DB6D7B800D> /usr/lib/dyld

Model: MacBookPro11,2, BootROM 478.0.0.0.0, 4 processors, Quad-Core Intel Core i7, 2.3 GHz, 16 GB, SMC 2.18f15
Graphics: kHW_IntelIrisProItem, Intel Iris Pro, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x02FE, -
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x02FE, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1680.11)
Bluetooth: Version 8.0.5d7, 3 services, 19 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM1024F, 1 TB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1

**Comment by duythanhle** [comment]
Turning off SIP may fix that problem.
