### ISSUE TITLE
Unable to open on mac

### ISSUE THREAD

**Issue by dirtycab** [j4nf4b3l/MDMPatcher-Universal#19]
Unable to open on mac, tells me cannot open because it cannot be checked for malicious malware?

**Comment by dirtycab** [comment]
edit: quits unexpectedly

**Comment by kennywong13104** [comment]
You could try to disable SIP on Mac. Search "Disable SIP mac" on web and try it.
The solution works on my case.

**Comment by crivera8602** [comment]
I second the disabling of SIP. It worked for me as well.
