### ISSUE TITLE
iPhone SE 2

### ISSUE THREAD

**Issue by 7DSMeliodas** [j4nf4b3l/MDMPatcher-Universal#2]
After patching device restarts but then the MDM is still there.

ios 15.5

**Comment by j4nf4b3l** [comment]
> After patching device restarts but then the MDM is still there.
> 
> 
> 
> ios 15.5

Make sure to factory reset your device using iTunes to latest version (or iOS 16 beta).
After that, activate the device using iTunes/Finder, do not connect to WiFi.
Then run MDMPatcher Universal, finish setup device. Then you can connect to WiFi and your device should work without any issues.

Hope that helps :)

**Comment by 7DSMeliodas** [comment]
Gonna try again

**Comment by 7DSMeliodas** [comment]
It worked !

**Comment by j4nf4b3l** [comment]
> It worked !

Very good! Enjoy :)

**Comment by Amratpal2002** [comment]
<plist/plist.h> file not found error on xcode please help

**Comment by truongvantuan** [comment]
> > After patching device restarts but then the MDM is still there.
> > ios 15.5
> 
> Make sure to factory reset your device using iTunes to latest version (or iOS 16 beta). After that, activate the device using iTunes/Finder, do not connect to WiFi. Then run MDMPatcher Universal, finish setup device. Then you can connect to WiFi and your device should work without any issues.
> 
> Hope that helps :)

You have save my life, it's worked
