### ISSUE TITLE
profile still exist 

### ISSUE THREAD

**Issue by asifclt** [j4nf4b3l/MDMPatcher-Universal#24]
i tried on ipad 5. it works well. but after long days i restored and again old mdm profile still showing. this method i used again to remove profile. cant be permanently remove this profile ?

**Comment by j4nf4b3l** [comment]
No. You can't remove the profile permanently like that. The tool only flashes a patched backup to the device to prevent the device contacting apple server and downloading the profile. 

If you want to permanently remove the profile, get in touch with the company showing up in the profile. Only them can remove it from apple DEP server.
