### ISSUE TITLE
Multiple iPads

### ISSUE THREAD

**Issue by jaykaso** [j4nf4b3l/MDMPatcher-Universal#3]
Hello! 

I have multiple iPads that are locked (they were e-wasted from a company) and they all are mdm. They are all on different OS, the latest is 15.5 on some. I disabled SIP and got the program to run but I still see the mdm after the device reboots, can I please get some help?

Thanks!

**Comment by j4nf4b3l** [comment]
Make sure to NOT login to Wi-Fi… Just activate over iTunes, then run the tool and setup…

**Comment by szalony9szymek** [comment]
restore the device, select language and region and don't go further! now activate in 3u and then run bypass. this worked for me on some random air 1 and it doesn't even show the mdm in the settings app!
