### ISSUE TITLE
MDMPatcher Universal quit unexpectedly

### ISSUE THREAD

**Issue by gettinghub** [j4nf4b3l/MDMPatcher-Universal#6]
OS: macOS Monterey Version 12.6
Device: iPad 7 iPadOS 15.2.1 on Hello Screen

Cannot open the application on my macbook
Error Message:
"MDMPatcher Universal quit unexpectedly
Click Report to see more detailed information and send a report to Apple."

**Comment by gettinghub** [comment]
Tried again with another laptop running macOS Mojave Version 10.14.6

Error Message:
"Check with the developer to make sure MDMPatcher
Universal works with this version of macOS. You may
need to reinstall the application. Be sure to install any
available updates for the application and macOS."

**Comment by XjSv** [comment]
Same here, getting the same error.
I'm on Ventura 13.0.

**Comment by vipkingo1** [comment]
Did you disable sip?

**Comment by XjSv** [comment]
Yeah I think that's the problem but I was running into issues disabling SIP because I'm running a hackintosh on Windows using VirtualBox.

**Comment by gettinghub** [comment]
Thanks! disabling SIP worked.
